# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: system\kernel\memory\Makefile
# desc: Compilation rules for this folder

include $(SYSTEM_PATH)\system.inc

OBJECTS = heap.o \
kheap.o \
uheap.o

all: $(OBJECTS)
clean:
	@$(RM) *.o
