# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: system\kernel\fs\Makefile
# desc: Compilation rules for this folder

include $(SYSTEM_PATH)\system.inc

OBJECTS = read.o \
write.o

all: $(OBJECTS)
clean:
	@$(RM) *.o
