# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: system\kernel\shell\Makefile
# desc: Compilation rules for this folder

include $(SYSTEM_PATH)\system.inc

OBJECTS = console.o \
kprintf.o

all: $(OBJECTS)
clean:
	@$(RM) *.o
