# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: lib\libc\stdio\Makefile
# desc: Compilation rules for this folder

include $(LIB_PATH)\lib.inc

OBJECTS = doprintf.o \
fgetc.o \
fgets.o \
fputc.o \
fputs.o \
getc.o \
getchar.o \
gets.o \
printf.o \
putc.o \
putchar.o \
puts.o \
sprintf.o \
vsprintf.o

all: $(OBJECTS)
clean:
	$(RM) *.o
