# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: system\kernel\process\Makefile
# desc: Compilation rules for this folder

include $(SYSTEM_PATH)\system.inc

OBJECTS = argument.o \
debug.o \
process.o \
thread.o

all: $(OBJECTS)
clean:
	@$(RM) *.o
