# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: lib\libc\string\Makefile
# desc: Compilation rules for this folder

include $(LIB_PATH)\lib.inc

OBJECTS = memcpy.o \
memmove.o \
memset.o \
strcat.o \
strchr.o \
strcmp.o \
strcpy.o \
strlen.o \
strncat.o \
strncmp.o \
strncpy.o \
strrchr.o

all: $(OBJECTS)
clean:
	$(RM) *.o
