# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: lib\libc\os\Makefile
# desc: Compilation rules for this folder

include $(LIB_PATH)\lib.inc

OBJECTS = exit.o \
read.o \
write.o

all: $(OBJECTS)
clean:
	$(RM) *.o
