# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: lib\Makefile
# desc: Compilation rules for this folder

include lib.inc

all:
	@echo "> Lib"
	@$(MAKE) -C libc
	@echo "> Done."
clean:
	@echo "> Cleaning lib"
	@$(MAKE) -C libc clean
	@echo "> Done."
