# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: lib\libc\math\Makefile
# desc: Compilation rules for this folder

include $(LIB_PATH)\lib.inc

OBJECTS = acos.o \
acosh.o \
asin.o \
asinh.o \
atan.o \
atan2.o \
atanh.o \
ceil.o \
cos.o \
cosh.o \
exp.o \
fabs.o \
floor.o \
fmod.o \
frexp.o \
hypot.o \
isnan.o \
ldexp.o \
log.o \
log10.o \
modf.o \
pow.o \
sin.o \
sinh.o \
sqrt.o \
tan.o \
tanh.o

all: $(OBJECTS)
clean:
	$(RM) *.o
