# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: lib\libc\sys\Makefile
# desc: Compilation rules for this folder

include $(LIB_PATH)\lib.inc

OBJECTS = float_dx.o \
huge_val.o \
int64.o

all: $(OBJECTS)
clean:
	$(RM) *.o
