# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: lib\libc\ctype\Makefile
# desc: Compilation rules for this folder

include $(LIB_PATH)\lib.inc

OBJECTS = ct_flags.o \
ct_lower.o \
ct_upper.o \
isalnum.o \
isalpha.o \
isascii.o \
iscntrl.o \
isdigit.o \
isgraph.o \
islower.o \
isprint.o \
ispunct.o \
isspace.o \
isupper.o \
isxdigit.o \
toascii.o \
tolower.o \
toupper.o

all: $(OBJECTS)
clean:
	$(RM) *.o
