# -- PCF Operating System  --
# See [docs\COPYRIGHT.txt] for more info
#
# file: lib\libc\stdlib\Makefile
# desc: Compilation rules for this folder

include $(LIB_PATH)\lib.inc

OBJECTS = abs.o \
atoi.o \
rand.o

all: $(OBJECTS)
clean:
	$(RM) *.o
